# chroot dir
---
- name: Make user chroot dir
  ansible.builtin.file:
    path: '{{ webuser.chroot_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Copy webuser.yml
  ansible.builtin.copy:
    src: '{{ webuser_yml }}'
    dest: '{{ webuser.chroot_dir }}/webuser.yml'
    owner: root
    group: root
    mode: '0755'

- name: Make dirs in user chroot
  ansible.builtin.file:
    path: '{{ webuser.chroot_dir }}{{ item.path }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: '{{ item.mode | default("0755") }}'
    state: directory
  loop:
    - { path: /dev }
    - { path: /etc }
    - { path: /home }
    - { path: /opt }
    - { path: /proc, mode: '0555' }
    - { path: /run }
    - { path: /srv }
    - { path: /sys, mode: '0555' }
    - { path: /tmp, mode: '1777' }
    - { path: /usr }
    - { path: /var }
    - { path: /var/log }
    - { path: /var/log/nginx }
    - { path: /var/log/httpd }
    - { path: /var/tmp, mode: '1777' }
    - { path: '{{ web_var_dir }}' }
    - { path: '{{ webuser.var_dir }}' }

- name: Make symlinks in user chroot
  ansible.builtin.file:
    src: '{{ item.to }}'
    dest: '{{ webuser.chroot_dir }}{{ item.path }}'
    force: true
    state: link
  loop:
    - { path: /bin, to: usr/bin }
    - { path: /lib, to: usr/lib }
    - { path: /lib64, to: usr/lib64 }
    - { path: /sbin, to: usr/sbin }
    - { path: /var/run, to: ../run }
    - { path: /var/lock, to: ../run/lock }

- name: Make loop chroot dir
  ansible.builtin.file:
    path: '{{ webuser.chroot_dir }}{{ webuser.chroot_dir | dirname }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Make loop symlink
  ansible.builtin.file:
    src: /
    dest: '{{ webuser.chroot_dir }}{{ webuser.chroot_dir }}'
    force: true
    state: link
