# mariadb
---
- name: Create user DB in MraiaDB
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
    name: '{{ webuser.name }}'

- name: Add user in MariaDB
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
    name: '{{ webuser.name }}'
    host: '%'
    password: '{{ webuser.db_pass }}'
    priv: '{{ webuser.name }}.*:ALL'
