# php-fpm
---
- name: Template php-fpm conf for user
  ansible.builtin.template:
    src: php-fpm.d/user.conf.j2
    dest: '/etc/php-fpm.d/{{ webuser.name }}.conf'
    owner: root
    group: root
    mode: '0644'
  register: template_php_fpm_conf

- name: Reload php-fpm
  ansible.builtin.systemd:
    name: 'php-fpm.service'
    state: reloaded
  when: template_php_fpm_conf.changed
