# web mount
---
- name: Enable and start web-mount for user
  ansible.builtin.systemd:
    name: 'web-mount@{{ webuser.name }}.service'
    enabled: true
    state: started

- name: Enable and start check-web-mount for user
  ansible.builtin.systemd:
    name: 'check-web-mount@{{ webuser.name }}.service'
    enabled: true
    state: started
