# conf web
---
- name: Role sv tls
  ansible.builtin.import_role:
    name: sv_tls

- name: Role sv fs client
  ansible.builtin.import_role:
    name: sv_fs_client

- name: Task nginx
  ansible.builtin.import_tasks: nginx.yml

- name: Task logrotate
  ansible.builtin.import_tasks: logrotate.yml

- name: Role lvs_dr
  ansible.builtin.import_role:
    name: sv_lvs_dr
  when: lvs_dr_addresses is defined

- name: Role vip
  ansible.builtin.import_role:
    name: sv_vip
  when: vip_addresses is defined
