# Gluster
---
- name: Install centos-release-gluster
  ansible.builtin.dnf:
    state: present
    name: 'centos-release-gluster{{ gluster_version }}'

# centos-release-gluster9はEL8に対して$relserverでは提供していないため、
# $streamに変更する必要がある。
# centos-relesae-gluster10では修正されている模様
- name: Fix Centos-Gluster-9.repo for EL8
  ansible.builtin.replace:
    path: /etc/yum.repos.d/CentOS-Gluster-9.repo
    regexp: '\$releasever'
    replace: '$stream'
  when:
    - gluster_version is version("9")
    - ansible_distribution_version is version("9", "<")

- name: Install glusterfs glusterfs-fuse
  ansible.builtin.dnf:
    state: present
    name:
      - glusterfs
      - glusterfs-fuse
