# Build glusterfs from source
# https://docs.gluster.org/en/main/Developer-guide/Building-GlusterFS/
---
- name: Set gluster_source_latest_url
  ansible.builtin.set_fact:
    gluster_source_latest_url: "https://download.gluster.org/pub/gluster/glusterfs/{{ gluster_version }}/LATEST/"

- name: Set gluster_source_latest_url_data
  ansible.builtin.set_fact:
    gluster_source_latest_url_data: >-
      {{ lookup("url", gluster_source_latest_url, headers={"Accept": "application/json"})
        | from_json }}

- name: Set gluster_source_latest_name
  ansible.builtin.set_fact:
    gluster_source_latest_name: >-
      {{ gluster_source_latest_url_data | selectattr("name", "search", "glusterfs-.*.tar.gz")
        | map(attribute="name") | first }}

- name: Set gluster_source_dir
  ansible.builtin.set_fact:
    gluster_source_dir: '{{ app_src_dir }}/{{ gluster_source_latest_name | regex_replace(".tar.gz$", "") }}'

# FIXME: 変えてしまっていいのだろうか？
- name: Chown app src dir
  become: true
  ansible.builtin.file:
    path: '{{ app_src_dir }}'
    state: directory
    owner: '{{ ansible_facts.user_id }}'
    mode: '0755'

- name: Get gluster source latest
  ansible.builtin.get_url:
    url: '{{ gluster_source_latest_url }}{{ gluster_source_latest_name }}'
    dest: '{{ app_src_dir }}/{{ gluster_source_latest_name }}'
    mode: '0644'

- name: Extract gluster source latest
  ansible.builtin.unarchive:
    src: '{{ app_src_dir }}/{{ gluster_source_latest_name }}'
    remote_src: true
    dest: '{{ app_src_dir }}/'
    creates: '{{ gluster_source_dir }}'

- name: Run autogen.sh
  ansible.builtin.command: ./autogen.sh
  args:
    chdir: '{{ gluster_source_dir }}'
  changed_when: true

- name: Run configure
  ansible.builtin.command: ./configure
  args:
    chdir: '{{ gluster_source_dir }}'
  changed_when: true

- name: Run make
  ansible.builtin.command: make
  args:
    chdir: '{{ gluster_source_dir }}'
  changed_when: true

- fail:
    msg: "STOP"
