# fs client - GlusterFS or NFS client
---
- name: Task glusterfs
  ansible.builtin.import_tasks: glusterfs.yml
  when: web_mount_fstype == "glusterfs"

- name: Task nfs
  ansible.builtin.import_tasks: nfs.yml
  when: web_mount_fstype == "nfs"
