# fs client - GlusterFS or NFS client
---
- name: Task gluster
  ansible.builtin.import_tasks: gluster.yml
  when: ansible_distribution_version is version("9", ">=")

- name: Task nfs
  ansible.builtin.import_tasks: nfs.yml
  when: ansible_distribution_version is version("9", "<")
