# NFS
---
- name: Install nfs-utils
  ansible.builtin.dnf:
    state: present
    name: nfs-utils

# {{ web_dir is mount }} では確認できないため ansible_mounts を使用する。
- name: Set web dir mounted
  ansible.builtin.set_fact:
    web_dir_mounted: '{{ web_dir in ansible_mounts | map(attribute="mount") }}'

- name: Set web mount server
  ansible.builtin.set_fact:
    web_mount_server: >-
      {{ gluster_cluster_servers[
        (groups["all"].index(inventory_hostname)) %
        (gluster_cluster_servers | length)] }}

# if mounted then mount after reboot
# else immediately mount
- name: Mount web dir nfs
  ansible.posix.mount:
    path: '{{ web_dir }}'
    src: '{{ web_mount_server }}:/{{ gluster_volume }}'
    fstype: nfs4
    opts: 'defaults,_netdev,minorversion=1'
    state: '{{ web_dir_mounted | ternary("present", "mounted") }}'
