---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  listen: 'reload firewalld'

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived.service
    state: restarted
  listen: 'restart keepalived'
