# enable repository
---
- name: Intall epel-relese
  ansible.builtin.dnf:
    state: present
    name: epel-release
  when: sv_app_repo == 'epel'

- name: Get repo list
  ansible.builtin.command:
    cmd: 'dnf repolist --enabled {{ sv_app_repo }}'
  register: dnf_repolist_enabled
  changed_when: false
  when: sv_app_repo != 'epel'

- name: Enable dnf repository
  ansible.builtin.command:
    cmd: 'dnf config-manager --set-enabled {{ sv_app_repo }}'
  changed_when: true
  when:
    - sv_app_repo != 'epel'
    - dnf_repolist_enabled.stdout == ""
