# app
---
- name: Set sv_app_versions
  ansible.builtin.set_fact:
    sv_app_versions: >-
      {{ sv_app_default_versions["el" ~ ansible_distribution_major_version][app_life_cycle]
        | combine(app_versions | default({})) }}

- name: Task app
  ansible.builtin.include_tasks: app.yml
  loop:
    - perl
    - python
    - php
    - ruby
    - nodejs
    - java
    - dotnet
    - gcc
    - clang
    - rust
    - golang
  loop_control:
    loop_var: sv_app_app

- name: Task pkg dev
  ansible.builtin.import_tasks: pkg_dev.yml
  when: app_dev

- name: Task pkg util
  ansible.builtin.import_tasks: pkg_util.yml
  when: app_util
