# Java
---
# 指定がない場合、最新バージョン("latset")が入ります。
- name: Install openjdk
  ansible.builtin.dnf:
    state: present
    name:
      - 'java-{{ item }}-openjdk'
      - 'java-{{ item }}-openjdk-devel'
  loop: '{{ sv_app_versions.java | default(["latest"]) }}'

# FIXME: うまくいかない
# - name: Select java
#   community.general.alternatives:
#     name: '{{ item }}'
#     path: '@java-{{ sv_app_versions.java | default(["latest"]) | first }}-openjdk.x86_64'
#   loop:
#     - java
#     - jre_openjdk
#     - javac
#     - java_sdk_openjdk

# alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-2.el9.x86_64/bin/java

# /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-3.el9.x86_64
