# Ruby
---
- name: Install ruby app stream
  ansible.builtin.dnf:
    state: present
    name: '@ruby:{{ sv_app_versions.ruby }}/common'
  when: sv_app_versions.ruby is defined

- name: Install ruby and extensions
  ansible.builtin.dnf:
    state: present
    name:
      - ruby
      - ruby-devel
      - rubygems-devel
      - rubygem-minitest
      - rubygem-power_assert
      - rubygem-rake
      - rubygem-test-unit
      - rubygem-mysql2
      - rubygem-pg

- name: Intall ruby other extensions for EL9
  ansible.builtin.dnf:
    state: present
    name:
      - ruby-default-gems
      - rubygem-irb
      - rubygem-rexml
      - rubygem-rss
      - rubygem-rbs
      - rubygem-typeprof
  when: ansible_distribution_major_version is version("9")

- name: Intall ruby bundled gems for EL9
  ansible.builtin.dnf:
    state: present
    name:
      - ruby-bundled-gems
  when:
    - ansible_distribution_major_version is version("9")
    - sv_app_versions.ruby | default("3.0") is version("3.1", ">=")

- name: Intall ruby other extensions for EL8
  ansible.builtin.dnf:
    state: present
    name:
      - ruby-irb
  when: ansible_distribution_major_version is version("8")
