# RHEL 9 Application Steraems
# https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel9_application_streams
---
- name: Install perl latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@perl:{{ sv_app_latest.el9.perl }}/common'
  when: sv_app_latest.el9.perl is defined

- name: Install perl
  ansible.builtin.dnf:
    state: present
    name:
      - perl
      - perl-devel
      - perl-CPAN
      - perl-CGI
      - perl-FCGI
      - perl-DBD-MariaDB
      - perl-DBD-MySQL
      - perl-DBD-Pg
      - perl-DBD-SQLite

- name: Install php latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@php:{{ sv_app_latest.el9.php }}/common'
  when: sv_app_latest.el9.php is defined

- name: Install php
  ansible.builtin.dnf:
    state: present
    name:
      - php
      - php-devel
      - php-gd
      - php-intl
      - php-ldap
      - php-mysqlnd
      - php-pecl-apcu
      - php-pgsql
      - php-soap

- name: Install ruby latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@ruby:{{ sv_app_latest.el9.ruby }}/common'
  when: sv_app_latest.el9.ruby is defined

- name: Install ruby
  ansible.builtin.dnf:
    state: present
    name:
      - ruby
      - ruby-devel
      - rubygems-devel
      - ruby-default-gems
      - ruby-bundled-gems
      - rubygem-irb
      - rubygem-minitest
      - rubygem-power_assert
      - rubygem-rake
      - rubygem-test-unit
      - rubygem-rexml
      - rubygem-rss
      - rubygem-rbs
      - rubygem-typeprof
      - rubygem-mysql2
      - rubygem-pg

- name: Install nodejs latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@nodejs:{{ sv_app_latest.el9.nodejs }}/common'
  when: sv_app_latest.el9.nodejs is defined

- name: Install nodejs
  ansible.builtin.dnf:
    state: present
    name:
      - nodejs

# multi version install

# Python 3.11 until 2026-05
- name: Install python 3.11
  ansible.builtin.dnf:
    state: present
    name:
      - python3.11
      - python3.11-devel
      - python3.11-pip
      - python3.11-PyMySQL
      - python3.11-psycopg2

# OpenJDK 1.8.0 until 2026-05
# OpenJDK 11 until 2024-10
# OpenJDK 17 until 2027-12
- name: Install openjdk
  ansible.builtin.dnf:
    state: present
    name:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - java-11-openjdk
      - java-11-openjdk-devel
      - java-17-openjdk
      - java-17-openjdk-devel

# no set alternatives
# - name: alternatives java
#   community.general.alternatives:
#     name: java

# .NET 6 until 2024-11 (LTS)
# .NET 7 until 2024-05
- name: Install dotnet
  ansible.builtin.dnf:
    state: present
    name:
      - dotnet-sdk-6.0
      - dotnet-sdk-7.0

# gcc-toolset 12 until 2024-11
- name: Install gcc-toolset
  ansible.builtin.dnf:
    state: present
    name:
      - gcc-toolset-12
  when: app_dev
