# RHEL 8 Full Life Application Steraems
# https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel8_full_life_application_streams
---
# - name: Install perl 5.26 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@perl:5.26/common'

# - name: Install perl
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - perl
#       - perl-devel
#       - perl-CPAN
#       - perl-CGI
#       - perl-FCGI
#       - perl-DBD-MySQL
#       - perl-DBD-Pg
#       - perl-DBD-SQLite

# - name: Install php 7.4 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@php:7.4/common'

# - name: Install php
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - php
#       - php-devel
#       - php-gd
#       - php-intl
#       - php-ldap
#       - php-mysqlnd
#       - php-pecl-apcu
#       - php-pgsql
#       - php-soap

# - name: Install ruby 2.5 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@ruby:2.5/common'

# - name: Install ruby
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - ruby
#       - ruby-devel
#       - ruby-irb
#       - rubygems-devel
#       - rubygem-minitest
#       - rubygem-power_assert
#       - rubygem-rake
#       - rubygem-test-unit
#       - rubygem-mysql2
#       - rubygem-pg

# multi version install

# # Python 3.6 full life
# - name: Install python 3.6 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@python36:3.6/common'

# - name: Install python
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - python3
#       - python3-devel
#       - python3-pip
#       - python3-PyMySQL
#       - python3-psycopg2
