# RHEL 8 Application Steraems
# https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel8_application_streams
---
# TODO: 下記のコンフリクトでうまくいかない
# perl:5.32/common Problems in request:
# Modular dependency problems with Defaults:
#  Problem: module perl:5.26:8050020211109115414:b4937e53.x86_64 conflicts with mo
# dule(perl:5.32) provided by perl:5.32:8080020230127034234:af169298.x86_64
#   - module perl:5.32:8080020230127034234:af169298.x86_64 conflicts with module(p
# erl:5.26) provided by perl:5.26:8050020211109115414:b4937e53.x86_64
#   - module freeradius:3.0:8080020230114090022:89170a74.x86_64 requires module(pe
# rl:5.26), but none of the providers can be installed
#   - conflicting requests"
# - name: Install perl latest app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@perl:{{ sv_app_latest.el8.perl }}/common'
#   when: sv_app_latest.el8.perl is defined

- name: Install perl
  ansible.builtin.dnf:
    state: present
    name:
      - perl
      - perl-devel
      - perl-CPAN
      - perl-CGI
      - perl-FCGI
      - perl-DBD-MySQL
      - perl-DBD-Pg
      - perl-DBD-SQLite

- name: Install php latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@php:{{ sv_app_latest.el8.php }}/common'
  when: sv_app_latest.el8.php is defined

- name: Install php
  ansible.builtin.dnf:
    state: present
    name:
      - php
      - php-devel
      - php-gd
      - php-intl
      - php-ldap
      - php-mysqlnd
      - php-pecl-apcu
      - php-pgsql
      - php-soap

- name: Install ruby latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@ruby:{{ sv_app_latest.el8.ruby }}/common'
  when: sv_app_latest.el8.ruby is defined

- name: Install ruby
  ansible.builtin.dnf:
    state: present
    name:
      - ruby
      - ruby-devel
      - ruby-irb
      - rubygems-devel
      - rubygem-minitest
      - rubygem-power_assert
      - rubygem-rake
      - rubygem-test-unit
      - rubygem-mysql2
      - rubygem-pg

- name: Install nodejs latest app stream
  ansible.builtin.dnf:
    state: present
    name: '@nodejs:{{ sv_app_latest.el8.nodejs }}/common'
  when: sv_app_latest.el8.nodejs is defined

- name: Install nodejs
  ansible.builtin.dnf:
    state: present
    name:
      - nodejs

# multi version install

# Python 3.11 until 2026-05
- name: Install python 3.11
  ansible.builtin.dnf:
    state: present
    name:
      - python3.11
      - python3.11-devel
      - python3.11-pip
      - python3.11-PyMySQL
      - python3.11-psycopg2

# OpenJDK 1.8.0 until 2026-05
# OpenJDK 11 until 2024-10
# OpenJDK 17 until 2027-12
- name: Install openjdk
  ansible.builtin.dnf:
    state: present
    name:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - java-11-openjdk
      - java-11-openjdk-devel
      - java-17-openjdk
      - java-17-openjdk-devel

# no set alternatives
# - name: alternatives java
#   community.general.alternatives:
#     name: java

# .NET 6 until 2024-11 (LTS)
# .NET 7 until 2024-05
- name: Install dotnet
  ansible.builtin.dnf:
    state: present
    name:
      - dotnet-sdk-6.0
      - dotnet-sdk-7.0

# gcc-toolset 12 until 2024-11
- name: Install gcc-toolset
  ansible.builtin.dnf:
    state: present
    name:
      - gcc-toolset-12

# - name: Install php 7.4 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@php:7.4/common'

# - name: Install php
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - php
#       - php-devel
#       - php-gd
#       - php-intl
#       - php-ldap
#       - php-mysqlnd
#       - php-pecl-apcu
#       - php-pgsql
#       - php-soap

# - name: Install ruby 2.5 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@ruby:2.5/common'

# - name: Install ruby
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - ruby
#       - ruby-devel
#       - ruby-irb
#       - rubygems-devel
#       - rubygem-minitest
#       - rubygem-power_assert
#       - rubygem-rake
#       - rubygem-test-unit
#       - rubygem-mysql2
#       - rubygem-pg

# - name: Install perl 5.26 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@perl:5.26/common'

# - name: Install perl
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - perl
#       - perl-devel
#       - perl-CPAN
#       - perl-DBD-MySQL
#       - perl-DBD-Pg
#       - perl-DBD-SQLite

# # multi version install

# # Python 3.6 full life
# - name: Install python 3.6 full life app stream
#   ansible.builtin.dnf:
#     state: present
#     name: '@python36:3.6/common'

# - name: Install python
#   ansible.builtin.dnf:
#     state: present
#     name:
#       - python3
#       - python3-devel
#       - python3-pip
#       - python3-PyMySQL
#       - python3-psycopg2
