# pkg util
---
- name: Install editors
  ansible.builtin.dnf:
    state: present
    name:
      - vim-enhanced
      - emacs-nox
      - nano
      - pinentry

- name: Install terminals
  ansible.builtin.dnf:
    state: present
    name:
      - tmux

- name: Install shell
  ansible.builtin.dnf:
    state: present
    name:
      - bash
      - tcsh
      - zsh

- name: Install others
  ansible.builtin.dnf:
    state: present
    name:
      - git
      - rsync
      - curl
      - wget

- name: Install others for el9
  ansible.builtin.dnf:
    state: present
    name:
      - lynx
  when: ansible_distribution_version is version("9", ">=")
