# Java
---
# 指定がない場合、最新バージョン("latset")が入ります。
- name: Install openjdk
  ansible.builtin.dnf:
    state: present
    name:
      - 'java-{{ item }}-openjdk'
      - 'java-{{ item }}-openjdk-devel'
  loop: '{{ sv_app_versions.java | default(["latest"]) }}'

- name: Get file stat alternative
  ansible.builtin.stat:
    path: '/etc/alternatives/java_sdk_{{ sv_app_versions.java | default(["latest"]) | first }}_openjdk'
  register: sv_app_java_sdk_openjdk

- name: Select java
  community.general.alternatives:
    name: '{{ item.name }}'
    path: '{{ sv_app_java_sdk_openjdk.stat.lnk_source }}{{ item.path | default("") }}'
  loop:
    - {name: java, path: /bin/java}
    - {name: jre_openjdk}
    - {name: javac, path: /bin/javac}
    - {name: java_sdk_openjdk}
