# hosts
---
- name: Bolck in hosts for db
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: '# {mark} ANSIBLE MANAGED BLOCK db'
    block: |
      127.0.0.2 db mariadb
      127.0.0.3 pg postgresql
