# db client
---

- name: Task hosts
  ansible.builtin.import_tasks: hosts.yml

- name: Task mariadb
  ansible.builtin.import_tasks: mariadb.yml

- name: Task postgresql
  ansible.builtin.import_tasks: postgresql.yml

- name: Task haproxy
  ansible.builtin.import_tasks: haproxy.yml
