## MariaDB
db_data_name: mysql
db_data_size: 16G
db_servers: '{{ groups["db"] | sort }}'
db_main_server: '{{ db_servers | first }}'
db_backup_servers: '{{ db_servers | difference([db_main_server]) | sort }}'
db_cluster_name: web_wsrep_cluster
db_character_set: utf8mb4
db_collation: utf8mb4_general_ci
