# restart app
---
- name: Restart php-fpm for user
  ansible.builtin.systemd:
    name: php-fpm.service
    state: restarted
  when:
    - httpd_php == "php-fpm"
    - '"httpd@" ~ user ~ ".service" in ansible_facts.services'

- name: Restart httpd for user
  ansible.builtin.systemd:
    name: 'httpd@{{ user }}.service'
    state: restarted
  when: '"httpd@" ~ user ~ ".service" in ansible_facts.services'

- name: Restart app for user
  ansible.builtin.systemd:
    name: 'app@{{ user }}.service'
    state: restarted
  when: '"app@" ~ user ~ ".service" in ansible_facts.services'
