# cert
---
- name: Create tursted CA certificate
  become: true
  ansible.builtin.copy:
    src: '{{ data_tls_ca_certs_dir }}/{{ item }}'
    dest: '/etc/pki/ca-trust/source/anchors/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ setup_trusted_cas }}'

# TODO: 必要なときだけ実行するようにする。
- name: Update CA trust
  become: true
  ansible.builtin.command: update-ca-trust
  changed_when: true
