# dnf設定
---
- name: Block in dnf.conf
  become: true
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    marker: '# {mark} ANSIBLE MANAGED BLOCK proxy'
    block: |
      proxy={{ proxy_uri }}
      timeout=600
  when: proxy_uri is defined

- name: Install environment group
  become: true
  ansible.builtin.dnf:
    state: present
    name: '@{{ setup_dnf_env_group }}'

- name: Install virtualization guest package for VMware
  become: true
  ansible.builtin.dnf:
    state: present
    name: open-vm-tools
  loop: "{{ ansible_facts.virtualization_tech_guest }}"
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "VMware"

- name: Install virtualization guest package for KVM
  become: true
  ansible.builtin.dnf:
    state: present
    name: qemu-guest-agent
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "kvm"

- name: Install management package for selinux
  become: true
  ansible.builtin.dnf:
    state: present
    name: policycoreutils-python-utils
  when: ansible_facts.selinux.status == "enabled"

- name: Install common packages
  become: true
  ansible.builtin.dnf:
    state: present
    name: '{{ setup_dnf_common_pkgs }}'
  when: setup_dnf_common_pkgs is defined
