---
- name: Set logrotate.conf rotate 15
  ansible.builtin.replace:
    path: /etc/logrotate.conf
    regexp: '^rotate\s+\d+$'
    replace: 'rotate 15'

- name: Set logrotate.conf dateext
  ansible.builtin.replace:
    path: /etc/logrotate.conf
    regexp: '^#?dateext$'
    replace: 'dateext'

- name: Set logrotate.conf compress
  ansible.builtin.replace:
    path: /etc/logrotate.conf
    regexp: '^#?compress$'
    replace: 'compress'
