# no mariadb
---
- name: Delete user in MraiaDB
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: absent
    name: '{{ webuser.name }}'
    host: '%'

- name: Drop user DB in MariaDB
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: absent
    name: '{{ webuser.name }}'
