# unmount
---
- name: Stop check-web-mount for user
  ansible.builtin.systemd:
    name: 'check-web-mount@{{ webuser.name }}.service'
    state: stopped

- name: Stop web-mount for user
  ansible.builtin.systemd:
    name: 'web-mount@{{ webuser.name }}.service'
    state: stopped
