# common vip
---
- name: Install Keepalived
  ansible.builtin.dnf:
    state: present
    name: keepalived

- name: Set vrrp_index
  ansible.builtin.set_fact:
    vrrp_index: '{{ groups[vip_group] | ansible.utils.index_of("eq", inventory_hostname) }}'

- name: Set vrrp_peers
  ansible.builtin.set_fact:
    vrrp_peers: >-
      {{
        (
          groups[vip_group] | map("extract", hostvars) | map(attribute="ansible_host") +
          groups[vip_group] | map("extract", hostvars) | map(attribute="inventory_ipv4", default=omit) +
          groups[vip_group] | map("extract", hostvars) | map(attribute="inventory_ipv6", default=omit)
        ) | ansible.utils.ipaddr | reject("in", [ansible_default_ipv4.address, ansible_default_ipv6.address])
      }}

- name: Template keepalived.cfg
  ansible.builtin.template:
    src: keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: 'restart keepalived'

- name: Enable and start keepalived
  ansible.builtin.systemd:
    name: keepalived.service
    enabled: true
    state: started
