# VS Code
# https://code.visualstudio.com/docs/setup/linux
---
# Visual Studio Code is unable to watch for file changes in this large workspace
- name: Copy max-users-watches template to sysctl.d
  ansible.builtin.template:
    src: 'sysctl.d/max-users-watches.conf.j2'
    dest: '/etc/sysctl.d/max-users-watches.conf'
    mode: '0644'
  notify: 'load sysctl max-users-watches'
