# dir
---
- name: Set SELinux file context for dir
  community.general.sefcontext:
    target: '{{ item.target }}'
    ftype: '{{ item.ftype | default("a") }}'
    selevel: '{{ item.selevel | default("s0") }}'
    setype: '{{ item.setype }}'
    seuser: '{{ item.seuser | default("system_u") }}'
  loop:
    - { target: '{{ web_dir }}/\w+/tmp', setype: tmp_t }

- name: Creaet systemd web-fs.target
  ansible.builtin.copy:
    src: systemd/web-fs.target
    dest: /etc/systemd/system/web-fs.target
    owner: root
    group: root
    mode: '0644'

- name: Enable systemd web-fs.target
  ansible.builtin.systemd:
    name: web-fs.target
    enabled: true
    state: started
    daemon_reload: true

- name: Creaet systemd web-mount@.service
  ansible.builtin.template:
    src: systemd/web-mount@.service.j2
    dest: /etc/systemd/system/web-mount@.service
    owner: root
    group: root
    mode: '0644'
  notify: 'reload systemd'
