# mgt
---
- name: Role sv user env
  ansible.builtin.import_role:
    name: sv_user_env

- name: Role sv app
  ansible.builtin.import_role:
    name: sv_app
  when: mgt_app

- name: Role sv fs client
  ansible.builtin.import_role:
    name: sv_fs_client

- name: Role sv db client
  ansible.builtin.import_role:
    name: sv_db_client

- name: Role sv web mount
  ansible.builtin.import_role:
    name: sv_web_mount
  vars:
    sv_web_mount_entries: '{{ conf_mgt_web_mount_entries }}'

- name: Task tls
  ansible.builtin.import_tasks: tls.yml

- name: Task sshd
  ansible.builtin.import_tasks: sshd.yml

- name: Task vsftpd
  ansible.builtin.import_tasks: vsftpd.yml

- name: Task nginx
  ansible.builtin.import_tasks: nginx.yml

- name: Task php
  ansible.builtin.import_tasks: php.yml

# userminで十分？なため、入れない
# - name: Task phpmyadmin
#   ansible.builtin.import_tasks: phpmyadmin.yml

# FIXME: 端末などで見えてしまうので、使わない。
# FIXME: http_port_tにすると起動しないので、リダイレクトできない。
# FIXME: リダイレクトがそもそもおかしい。
# - name: Task cockpit
#   ansible.builtin.import_tasks: cockpit.yml

- name: Task usermin
  ansible.builtin.import_tasks: usermin.yml
