# sshd
---
- name: Set seboolean use fusefs hom dirs
  ansible.posix.seboolean:
    name: use_fusefs_home_dirs
    state: true
    persistent: true

- name: Copy users.conf
  ansible.builtin.copy:
    src: sshd/users.conf
    dest: /etc/ssh/sshd_config.d/users.conf
    mode: '0600'
  notify: 'restart sshd'

- name: Set ssh service in firewalld
  ansible.posix.firewalld:
    state: enabled
    service: ssh
    permanent: true
  notify: 'reload firewalld'
