# health check
---
- name: Task system
  ansible.builtin.import_tasks: system.yml

- name: Task disk
  ansible.builtin.import_tasks: disk.yml

- name: Task mount
  ansible.builtin.import_tasks: mount.yml
  when: group_names | intersect(["mgt", "bk", "app", "web", "test"]) | length > 0

- name: Task service
  ansible.builtin.import_tasks: service.yml

- name: Task lvm pool
  ansible.builtin.import_tasks: lvm_pool.yml
  when: '"fs" in group_names'
