# service
---
- name: Fact serivce
  ansible.builtin.service_facts:
  when: ansible_facts.services is not defined

- name: Check service
  ansible.builtin.assert:
    that: false
    msg: 'service failed'
    quiet: true
  loop: >-
    {{ ansible_facts.services.values()
      | selectattr("name", "search", "\.service$")
      | rejectattr("name", "search", "@\.service$")
      | rejectattr("name", "in", health_check_service_ignore_list)
      | rejectattr("status", "in", [
        "active", "enabled", "enabled-runtime", "static",
        "inactive","disabled",
        "indirect", "alias", "not-found", "masked",
      ])
    }}
  loop_control:
    label: "{{ item.name }} {{ item.status }}"
