# service
---
- name: Fact serivce
  ansible.builtin.service_facts:
  when: ansible_facts.services is not defined

- name: Check service
  ansible.builtin.assert:
    that: item.state in ["running", "active", "inactive", "stopped"]
    msg: 'service failed or unknown state'
    quiet: true
  loop: >-
    {{ ansible_facts.services.values()
       | selectattr("status", "in", ["enabled", "active"])
       | selectattr("name", "search", "\.service$")
       | rejectattr("name", "search", "@\.service$")
    }}
  loop_control:
    label: "{{ item.name }} {{ item.state }}"
