## PostgreSQL
pg_servers: '{{ groups["db"] | sort | reverse }}'
pg_main_server: '{{ pg_servers | first }}'
pg_backup_servers: '{{ pg_servers | difference([pg_main_server]) | sort | reverse }}'
pg_replication_user: replicator
# pg_replication_password: set password
pg_data_name: pgsql
pg_data_size: 16G
