---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  listen: 'reload firewalld'

- name: Reload systed
  ansible.builtin.systemd:
    daemon_reload: true
  listen: 'reload systemd'

- name: Reload nfs-ganesha
  ansible.builtin.systemd:
    name: nfs-ganesha.service
    state: reloaded
  listen: 'reload nfs-ganesha'
