# Gluster + NFS-Ganesha
---
- name: Install centos-release-nfs-ganesha
  ansible.builtin.dnf:
    state: present
    name: 'centos-release-nfs-ganesha{{ nfs_ganesha_version }}'

- name: Enable highavailability repository
  ansible.builtin.import_role:
    name: sv_app
    tasks_from: enable_repo
  vars:
    sv_app_repo: highavailability

- name: Install glusterfs-ganesha
  ansible.builtin.dnf:
    state: present
    name: glusterfs-ganesha

- name: Config ganesha.conf
  ansible.builtin.template:
    src: ganesha/ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
    mode: '0644'
    owner: root
    group: root
  notify: 'restart nfs-ganesha'

- name: Make systemd nfs-ganesha.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/nfs-ganesha.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

# FIXME: nfsganeshaがコア吐いて落ちる場合がある。
- name: Copy systemd conf nfs-ganesha.service.d
  ansible.builtin.copy:
    src: 'systemd/{{ item }}'
    dest: '/etc/systemd/system/nfs-ganesha.service.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - restart.conf
  notify: 'reload systemd'

- name: Enable and start nfs-ganesha
  ansible.builtin.systemd:
    name: nfs-ganesha.service
    enabled: true
    state: started
