# glusnter main
---
- name: Gluster prove peer
  gluster.gluster.gluster_peer:
    state: present
    nodes: '{{ gluster_servers }}'

- name: Check cluster replicas
  ansible.builtin.assert:
    that: ((gluster_cluster_servers | length) % gluster_cluster_replicas) == 0
    msg: 'number of gluster cluster servers is not a mutiple of {{ gluster_cluster_replicas }}'
    quiet: true

- name: Gluster create volume
  gluster.gluster.gluster_volume:
    state: present
    name: '{{ gluster_volume }}'
    replicas: '{{ gluster_cluster_replicas }}'
    bricks: '{{ gluster_data_dir }}/{{ gluster_volume }}'
    cluster: '{{ gluster_cluster_servers }}'

- name: Get gluster snapshot config
  ansible.builtin.command:
    argv:
      - /usr/sbin/gluster
      - snapshot
      - config
      - '{{ gluster_volume }}'
  changed_when: false
  register: gluster_snapshot_config

- name: Set fact gluster_sanpshot_config_hard
  ansible.builtin.set_fact:
    gluster_snapshot_config_hard: >-
      {{ gluster_snapshot_config.stdout_lines
        | select("match", "Effective snap-max-hard-limit : \d+")
        | first
        | split
        | last
      }}
  when: gluster_snapshot_config.stdout_lines | length > 0

- name: Set gluster snapshot config snap-max-hard-limit
  ansible.builtin.command:
    argv:
      - /usr/sbin/gluster
      - snapshot
      - config
      - '{{ gluster_volume }}'
      - snap-max-hard-limit
      - '{{ gluster_snapshot_hard }}'
    stdin: 'y'
  changed_when: true
  when:
    - gluster_snapshot_config_hard is defined
    - gluster_snapshot_config_hard | int != gluster_snapshot_hard

- name: Get gluster volume get all
  ansible.builtin.command:
    argv:
      - /usr/sbin/gluster
      - volume
      - get
      - '{{ gluster_volume }}'
      - all
  changed_when: false
  register: gluster_volume_get_all

# for NFS-Ganesha
- name: Set gluster volume set features.cache-invalidation on
  ansible.builtin.command:
    argv:
      - /usr/sbin/gluster
      - volume
      - set
      - '{{ gluster_volume }}'
      - features.cache-invalidation
      - 'on'
    stdin: 'y'
  changed_when: true
  when:
    - gluster_volume_get_all.stdout_lines | length > 0
    - >-
      (gluster_volume_get_all.stdout_lines
        | select("match", "features.cache-invalidation")
        | first | split)[1] == "off"
