# proxy
---
- name: Copy login shell template in profile.d
  ansible.builtin.template:
    src: 'profile.d/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '0644'
  loop:
    - proxy.sh
    - proxy.csh
  when: proxy_env is defined
