---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  listen: 'reload firewalld'

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
  listen: 'restart nginx'
