---
- name: Reboot all servers expect ctl
  hosts:
    - all
    - '!ctl'
  become: true
  serial: 1
  max_fail_percentage: 0
  roles:
    - role: reboot
      when: id is not defined or inventory_hostname_short[-1:] == id
