- name: Update in permsinnive all except ctl
  hosts:
    - all
    - '!ctl'
  become: true
  serial: 1
  max_fail_percentage: 0
  roles:
    - role: update_in_permissive
      when:
        - id is not defined or inventory_hostname_short[-1:] == id
        - group is not defined or group in group_names
