- name: Update and reboot all except ctl
  hosts:
    - all
    - '!ctl'
  become: true
  serial: 1
  max_fail_percentage: 0
  roles:
    - role: update_reboot
      when: id is not defined or inventory_hostname_short[-1:] == id
