---
- name: Stat file
  ansible.builtin.stat:
    path: '{{ item }}'
  register: file_stat

- name: Check no file
  ansible.builtin.assert:
    that: not file_stat.stat.exists
    msg: 'File exists: {{ item }}'
    quiet: true
