---
- name: Stat file
  ansible.builtin.stat:
    path: '{{ item }}'
  register: file_stat

- name: Copy file
  ansible.builtin.copy:
    remote_src: true
    src: '{{ item }}'
    dest: '{{ item }}.{{ backup_time }}'
    mode: '{{ file_stat.stat.mode }}'
    force: false
  when: file_stat.stat.exists

- name: Delete file
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  when: file_stat.stat.exists
