# dir
---
- name: Make public_html (dummy document)
  ansible.builtin.file:
    path: /public_html
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Make web var dir
  ansible.builtin.file:
    path: '{{ web_var_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Set SELinux file context for dir
  community.general.sefcontext:
    target: '{{ item.target }}'
    ftype: '{{ item.ftype | default("a") }}'
    selevel: '{{ item.selevel | default("s0") }}'
    setype: '{{ item.setype }}'
    seuser: '{{ item.seuser | default("system_u") }}'
  loop:
    - { target: '{{ web_dir }}/\w+/tmp', setype: tmp_t }
    - { target: '{{ web_var_dir }}/\w+/lib(/.*)?', setype: var_lib_t }
    # - { target: '{{ web_var_dir }}/\w+/lock', ftype: d, setype: var_lock_t }
    # - { target: '{{ web_var_dir }}/\w+/lock', ftype: l, setype: var_lock_t }
    # - { target: '{{ web_var_dir }}/\w+/log', ftype: d, setype: var_log_t }
    # - { target: '{{ web_var_dir }}/\w+/log/.*', setype: var_log_t }
    # - { target: '{{ web_var_dir }}/\w+/run', ftype: d, setype: var_run_t }
    # - { target: '{{ web_var_dir }}/\w+/run', ftype: l, setype: var_run_t }
    # - { target: '{{ web_var_dir }}/\w+/run/.*', setype: var_run_t }
    # - { target: '{{ web_var_dir }}/\w+/tmp', ftype: d, setype: tmp_t }
    # - { target: '{{ web_var_dir }}/\w+/tmp', ftype: l, setype: tmp_t }
  notify: 'run restorecon'

- name: Creaet systemd web-fs.target
  ansible.builtin.copy:
    src: systemd/web-fs.target
    dest: /etc/systemd/system/web-fs.target
    owner: root
    group: root
    mode: '0644'

- name: Creaet systemd web-fs.target
  ansible.builtin.systemd:
    name: web-fs.target
    enabled: true
    state: started
    daemon_reload: true

- name: Creaet systemd web-mount@.service
  ansible.builtin.template:
    src: systemd/web-mount@.service.j2
    dest: /etc/systemd/system/web-mount@.service
    owner: root
    group: root
    mode: '0644'
  notify: 'reload systemd'
