# dir
---
- name: Make public_html (dummy document)
  ansible.builtin.file:
    path: /public_html
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Make web var dir
  ansible.builtin.file:
    path: '{{ web_var_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Set SELinux file context for dir
  community.general.sefcontext:
    target: '{{ item.target }}'
    ftype: '{{ item.ftype | default("a") }}'
    selevel: '{{ item.selevel | default("s0") }}'
    setype: '{{ item.setype }}'
    seuser: '{{ item.seuser | default("system_u") }}'
  loop:
    - { target: '{{ web_var_dir }}/\w+/lib(/.*)?', setype: var_lib_t }
  notify: 'run restorecon'
