# msmtp
---
# - name: Install epel-release
#   ansible.builtin.dnf:
#     state: present
#     name: epel-release

- name: Include task enable repo from sv_app
  ansible.builtin.include_role:
    name: sv_app
    tasks_from: enable_repo
  vars:
    sv_app_repo: 'epel'

- name: Install msmtp
  ansible.builtin.dnf:
    state: present
    name: msmtp

- name: Task semodule for local_msmtp
  ansible.builtin.import_tasks:
    file: semodule.yml
  vars:
    semodule_name: local_msmtp

- name: Template msmtprc
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: '0644'
