# php-fpm
---
- name: Install php-fpm
  ansible.builtin.dnf:
    state: present
    name: php-fpm

- name: Make systemd php-fpm.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/php-fpm.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy systemd conf php-fpm.service.d
  ansible.builtin.copy:
    src: 'systemd/{{ item }}'
    dest: '/etc/systemd/system/php-fpm.service.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - dependencies.conf
  notify: 'reload systemd'

- name: Enable and start php-fpm
  ansible.builtin.systemd:
    name: php-fpm.service
    enabled: true
    state: started
