# update and reboot if necessary
---
- name: Role update
  ansible.builtin.import_role:
    name: update

- name: Role reboot
  ansible.builtin.import_role:
    name: reboot
  when: update_reboot_force or update_reboot_requierd

- name: Role check update
  ansible.builtin.import_role:
    name: update_check
